[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/dev/stdout
redirect_stderr=true

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
redirect_stderr=true
